name: Hugo CD

on:
  push:
    branches:
      - "master"

defaults:
  run:
    working-directory: ./

jobs:
  cd:
    timeout-minutes: 6
    name: CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: Build
        run: hugo -D -F
      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://maik.dev/
          environment: production
          initial_status: "success"
