name: Hugo CI

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!master"
  pull_request:
    branches:
      - "master"

defaults:
  run:
    working-directory: ./

jobs:
  ci:
    timeout-minutes: 5
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo -D -F
